name: mobilekey_ui
description: "WebKey.ID is a app to open locks everywhere."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.5
  dependencies:
  graphql_flutter: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/data.json
    - assets/images/
    
  uses-material-design: true
