name: mobilekey_ui
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/data.json
    - assets/images/logo-small.png
    - assets/images/bitcoin-black-icon.png
  uses-material-design: true
